### ISSUE TITLE
Study SQLite3 parser

### ISSUE THREAD

**Issue by pateljm** [UWHustle/hustle#1]
We want Hustle to be compatible with the SQLite3 parser (we aim for Hustle's language surface to be a  superset of SQLite3). The goal here is to determine if we can rip SQLite3's parser and output a plan in JSON that can then be ingested by the Hustle Query Processor.

Start by [understanding SQLite3's architecture](https://www.sqlite.org/arch.html). 

Looking forward, we will also focus on creating an [SQLAlchemy](http://www.sqlalchemy.org/) binding to Hustle. [Here is an nice SQLAlchemy tutorial](https://www.pythoncentral.io/introductory-tutorial-python-sqlalchemy/).

**Comment by gaffneyk** [comment]
Our conclusion is that the SQLite3 parser is likely too tightly integrated with the rest of the system to be extracted as a module. In SQLite3, the parser calls code generator functions that assemble the bytecode instructions. There is no intermediate parse tree (that we know of).

**Comment by pateljm** [comment]
Sounds good. Let go explore using our own parser.
