### ISSUE TITLE
blink tree加锁问题

### ISSUE THREAD

**Issue by mengqingzhong** [UWHustle/hustle#114]
您好，我在https://stackoverflow.com/questions/58478390/blink-tree-insert-operation看到您回答了一个blink tree的问题。我不明白的是，为什么在parent层向右移动的时候，需要先拿右边的锁，然后再释放左边的锁。PostgreSQL实现blink tree的时候，没有采用这种chain lock的方式，而是直接先放左边的，然后拿右边的锁。我的邮箱是mengqingzhong.gm[at]gmail.com，期待您的回复。

**Comment by GindaChen** [comment]
Thanks for asking! Let's route the conversation on the [original stackoverflow page](https://stackoverflow.com/questions/58478390/blink-tree-insert-operation). It's indeed a pretty interesting question, and I have no immediate answer right now...
