### ISSUE TITLE
Support Aggregation queries

### ISSUE THREAD

**Issue by johnchronis** [UWHustle/hustle#16]
Target: Running by 12/21/2018

This issue will track the necessary steps needed to support the following queries end to end in Hustle:
- SELECT SUM(a) FROM t;
- SELECT COUNT(a) FROM t;
- SELECT CommonPrefix(a) FROM t;

Parser: Supported

Optimizer: 
- Sum and Count Supported.
- Need to add support for custom aggregation functions

Execution Engine: 
- Needs support for deserialization of the optimizer output containing aggregations.
- Sum and Count Supported.
- Need to add support for custom aggregation functions

**Comment by mattdutson** [comment]
Standard aggregations now supported (`SUM`, `COUNT`, `MIN`, `MAX`, `AVG`). Closing this issue.
