### ISSUE TITLE
Study Quickstep parser

### ISSUE THREAD

**Issue by gaffneyk** [UWHustle/hustle#3]
We want to determine if we can rip out the [Quickstep](https://github.com/apache/incubator-quickstep) parser and use it as a module. The input to the module would be a SQL string and the output would be a JSON query plan that can be accepted by the query processor.

If this is possible, we will determine what modifications need to be made in order to match the language surface of SQLite3.

**Comment by johnchronis** [comment]
Can we close this?

**Comment by mattdutson** [comment]
Yes I think so.

**Comment by johnchronis** [comment]
A new parser will be implemented for Hustle.
