### ISSUE TITLE
Create Table

### ISSUE THREAD

**Issue by srora** [UWHustle/hustle#53]
Support Create Table and Insert Into queries in execution engine.
We should be able to run the following queries :

```sql
      CREATE TABLE table_name (
      column_1 data_type_1,
      column_2 data_type_2,
      ...
      );
```

```sql
      INSERT INTO table_name
      VALUES (value1,  value2, ...);
```

**Comment by johnchronis** [comment]
#55 updates the catalog that is maintained in the optimizer when a create or drop table query is optimized.

**Comment by srora** [comment]
Issue : "Memory mapped can not have length 0."

**Comment by johnchronis** [comment]
@srora can you elaborate? when are you getting this error?
